# List

<h2>Soal 1: Sifat List</h2>

Jawab Pertanyaan di bawah ini:

Jenis data apa saja yang bisa ada di dalam List?

semua tipe data baik primitive maupun non primitive bisa ada di dalam list. source : https://www.tecmint.com/learn-python-list-data-structure/

<h2>Soal 2: Akses List</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [2]:
a = ['1', '13b', 'aa1', 1.32, 22.1, 2.34]
print(a[1:len(a)-1])

['13b', 'aa1', 1.32, 22.1]


Expected Output :

[ '13b', 'aa1', 1.32, 22.1 ]

<h2>Soal 3: Nested List</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [3]:
a = [1.32, 22.1, 2.34]
b = ['1', '13b', 'aa1']
c = [3, 40, 100]
l = [a,c,b]
print(l)

[[1.32, 22.1, 2.34], [3, 40, 100], ['1', '13b', 'aa1']]


Expected Output :

[ [1.32, 22.1, 2.34], [3, 40, 100], ['1', '13b', 'aa1'] ]

<h2>Soal 4: Akses Nested List</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [5]:
a = [
    [5, 9, 8],
    [0, 0, 6]
    ]
print([a[1][0],a[1][2]])

[0, 6]


Expected Output :


[0, 6]

<h2>Soal 5: Built in Function List</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [22]:
p = [0, 5, 2, 10, 4, 9]
p.sort(reverse=False)
print(f"{p}\n\n{max(p)}")

[0, 2, 4, 5, 9, 10]

10


Expected Output :

[0, 2, 4, 5, 9, 10]

10

<h2>Soal 6: List Operation</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [30]:
a = [1, 3, 5]
b = [5, 1, 3]
print(b+a)

[5, 1, 3, 1, 3, 5]


Expected Output :

[5, 1, 3, 1, 3, 5]

<h2>Soal 7: List Manipulation</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [31]:
a = [
    [5, 9, 8],
    [0, 0, 6]
    ]
a[0][2] = 10
a[1][0] = 11
print(a)

[[5, 9, 10], [11, 0, 6]]


Expected Output :

[ [5, 9, 10], [11, 0, 6] ]

<h2>Soal 8: Delete Element List</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [33]:
areas = ["hallway", 11.25, "kitchen", 18.0,
        "chill zone", 20.0, "bedroom", 10.75,
         "bathroom", 10.50, "poolhouse", 24.5,
         "garage", 15.45]

# Hilangkan elemen yang bernilai "bathroom" dan 10.50 dalam satu statement code
del areas[8:10]
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'poolhouse', 24.5, 'garage', 15.45]


Expected Output:

['hallway',
 11.25,
 'kitchen',
 18.0,
 'chill zone',
 20.0,
 'bedroom',
 10.75,
 'poolhouse',
 24.5,
 'garage',
 15.45]



## Soal 9: List Comprehension

Gunakan metode **list comprehension** untuk mencari anggota dari S yang habis di bagi 2, kemudian assign hasilnya dalam bentuk list ke dalam variabel T.

In [36]:
S = [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

T = [i for i in S if i%2==0]

print(T)

[0, 4, 16, 36, 64]


Expected Output:

[0, 4, 16, 36, 64]

# Dictionary

<h2>Soal 10: Akses Dictionary</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [38]:
europe = {'spain':'madrid', 'france':'paris', 'germany':'berlin', 'norway':'oslo' }

# print semua key yang ada di objek europe
print(europe.keys())
# print nilai dari key franche
print(europe['france'])

dict_keys(['spain', 'france', 'germany', 'norway'])
paris


Expected Output:

dict_keys(['spain', 'france', 'germany', 'norway'])

paris

<h2>Soal 11: Menambahkan key-value baru ke Dictionary</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [39]:
europe = {'spain':'madrid', 'france':'paris', 'germany':'berlin', 'norway':'oslo' }

# tambahkan key itali ke objek dictionary dengan value roma
europe['itali'] = 'roma'

# cek apakah itali ada di dalam objek dictionary
print('itali' in europe)

True


Expected Output:
    
True

<h2>Soal 12: Update dan Remove Dictinary</h2>
    
Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [41]:
europe = {'spain':'madrid', 'france':'paris', 'germany':'bonn',
          'norway':'oslo', 'italy':'rome', 'poland':'warsaw',
          'australia':'vienna' }

# update nilai ibukota german ke berlin
europe.update({'germany':'berlin'})

# remove australia dari europa
europe.pop('australia')

print(europe)

{'spain': 'madrid', 'france': 'paris', 'germany': 'berlin', 'norway': 'oslo', 'italy': 'rome', 'poland': 'warsaw'}


Expected Output:

{'spain': 'madrid', 'france': 'paris', 'germany': 'berlin', 'norway': 'oslo', 'italy': 'rome', 'poland': 'warsaw'}

<h2>Soal 13: Nested Dictionary</h2>
    
Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [58]:
country = { 
           'spain': { 'capital':'madrid', 'population':46.77 },
           'france': { 'capital':'paris', 'population':66.03 },
           'germany': { 'capital':'berlin', 'population':80.62 },
           'norway': { 'capital':'oslo', 'population':5.084 } 
         }

# berapa populasi dari kota german?
print(country['germany']['population'])

# update data baru, yaitu negara indonesia dengan capital jakarta dan poulasi 250
a = {'capital':'jakarta', 'population':250}
country.update({'indonesia':a})
print(country)

80.62
{'spain': {'capital': 'madrid', 'population': 46.77}, 'france': {'capital': 'paris', 'population': 66.03}, 'germany': {'capital': 'berlin', 'population': 80.62}, 'norway': {'capital': 'oslo', 'population': 5.084}, 'indonesia': {'capital': 'jakarta', 'population': 250}}


Expected Output:

80.62

{'spain': {'capital': 'madrid', 'population': 46.77}, 'france': {'capital': 'paris', 'population': 66.03}, 'germany': {'capital': 'berlin', 'population': 80.62}, 'norway': {'capital': 'oslo', 'population': 5.084}, 'indonesia': {'capital': 'jakarta', 'population': 250}}

<h2>Soal 14: Loop Dictionary</h2>
    
Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [66]:
country = { 
           'spain': { 'capital':'madrid', 'population':46.77 },
           'france': { 'capital':'paris', 'population':66.03 },
           'germany': { 'capital':'berlin', 'population':80.62 },
           'norway': { 'capital':'oslo', 'population':5.084 },
           'indonesia' : {'capital':'jakarta', 'population':250}
         }

for i in country:
    print(f"ibukota {i} adalah {country[i]['capital']}")

ibukota spain adalah madrid
ibukota france adalah paris
ibukota germany adalah berlin
ibukota norway adalah oslo
ibukota indonesia adalah jakarta


Expected Output:
    
Ibukota spain adalah madrid

Ibukota france adalah paris

Ibukota germany adalah berlin

Ibukota norway adalah oslo

Ibukota indonesia adalah jakarta

In [1]:
new_list = []
def remove_duplicate(list):
    i = 0
    j = 1
    while i < len(list):
        while j <len(list):
            if list[i]==list[j]:
                del list[j]
                j +=1
            else:
                j+=1
        i+=1
        j=i+1
    new_list = list[:]
    return new_list

def remove_duplicate_with_set(list):
    new_list = set(list)
    return new_list 

obj_list = [1, 2, 4, 6, 2, 1, 4, 5, 7, 8, 6]
print(remove_duplicate(obj_list))
print(remove_duplicate_with_set(obj_list))




[1, 2, 4, 6, 5, 7, 8]
{1, 2, 4, 5, 6, 7, 8}


In [2]:
from datetime import datetime
import random
nama = "Wahyu"
tanggal = datetime.now().day
default = "maaf, aku tidak tahu jawaban dari pertanyaanmu"

jawaban_nama = [
    "nama saya  {0}".format(nama),
    "orang-orang memanggil saya {0}".format(nama),
    "panggil saja saya {0}".format(nama)
]

jawaban_tanggal = [
    "hari ini tanggal {0}".format(tanggal),
    "ya ampun masa tidak tahu, hari ini tanggal".format(tanggal)
]

pertanyaan = {
    "nama kamu siapa?": jawaban_nama,
    "kamu siapa?": jawaban_nama,
    "tanggal berapa hari ini?": jawaban_tanggal,
    "hari ini tanggal berapa?": jawaban_tanggal,
    "default": default
}

statement = [
    'ceritakan lebih banyak!',
    'kenapa kamu berpikir begitu?',
    'sudah berapa lama kamu merasa seperti ini?',
    'Itu sangat menarik!',
    'oh wow!',
    ':)'
]

responses = {
    'pertanyaan': pertanyaan,
    'statement': statement
}



def chatbot(message):
    a= ''
    print('Saya :',message)
    if "?" in message:
        if 'siapa' in message:
            a = random.choices(jawaban_nama)
        elif 'hari' in message:
            a =random.choices(jawaban_tanggal)
        else:
            a = default
    else:
        a = random.choices(statement)
    return str(a).strip("'[]")

print(chatbot('Selamat Pagi'))
print(chatbot('Mau bermain bersamaku?'))
print(chatbot('nama kamu siapa?'))
print(chatbot('hari ini tanggal berapa?'))



Saya : Selamat Pagi
ceritakan lebih banyak!
Saya : Mau bermain bersamaku?
maaf, aku tidak tahu jawaban dari pertanyaanmu
Saya : nama kamu siapa?
nama saya  Wahyu
Saya : hari ini tanggal berapa?
hari ini tanggal 2
